<Button>
    font_size:20
    color:0.3,0.4,0.5,1
    size_hint:0.1, 0.1


<BoxLayout>
    orientation:'horizontal'
    spacing:10

    Button:
        text: "Submit"
        background_color: 0.3,0.5,0.5,1
        on_press:

    Button:
        id:btn
        text: "Clear"
        background_color: 0.3,0.4,0.5,1
        on_press:

    GridLayout:

        cols:2
        Label:
            text: "Name: "                
        TextInput:
            multiline:False